on:
  push:

jobs:
  check_custom_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      - name: Check Custom Properties
        run: |
          # Debug: Listar arquivos para confirmar o diretório de execução
          echo "--- Arquivos no diretório atual ---"
          ls -R
          
          # Obtendo todas as custom properties em formato JSON
          PROPS_JSON='${{ toJSON(github.event.repository.custom_properties) }}'
          echo "--- Custom Properties JSON ---"
          echo "$PROPS_JSON"
          
          # Verifica se 'VPC' está presente nas propriedades
          if echo "$PROPS_JSON" | grep -q '"VPC"'; then
            
            module "my_networking" {
            source            = "github.com/robthross/terraform_aws//modules/networking?ref=main"
            vpc_cidr          = "10.0.0.0/16"
            subnet_cidr       = "10.0.1.0/24"
            availability_zone = "us-east-2a"
              }
            
            terraform init -input=false
            terraform plan -input=false -no-color
          fi
          
          # Verifica se 'SQS' está presente nas propriedades
          if echo "$PROPS_JSON" | grep -q '"SQS"'; then
            echo "--- Alvo: SQS detectado ---"
            echo "Provicionando Instancia"
            terraform init -input=false
            terraform plan -input=false -no-color
          fi

  compara_diretorios:
    needs: check_custom_properties
    uses: robthross/gitactions/.github/workflows/check-template.yml@develop
