name: Sync Template
on:
  push:

jobs:
  compara_diretorios:   
      uses: rtechthiago/check-template/.github/workflows/check-template.yml@main
      permissions: write-all
      secrets: inherit

      